Repository nanvix/nanvix, pull requests merged in 2018-05, with the labels that each got.

#194 Issue 184 Bug Fix
  src/kernel/arch/x86/utilities.S
Labels: bug, x86

#195 Issue 185 Bug Fix
  src/kernel/arch/x86/utilities.S
Labels: bug, x86

#196 Issue 186 Bug Fix
  src/kernel/arch/x86/utilities.S
Labels: bug, x86

#197 Issue 188 Bug Fix
  src/kernel/mm/paging.c
Labels: bug, x86

#203 Upating QEMU to Version 2.12.0
  tools/dev/setup-qemu.sh
Labels: enhancement

#224 or1k, bug fix: issue #222, cannot create semaphores
  include/nanvix/syscall.h
  src/kernel/sys/semopen.c
Labels: bug, or1k

#225 or1k, bug fix: bad var_args arguments when type is bigger than 4 bytes
  include/stdarg.h
  src/kernel/dev/ata/ata.c
  src/kernel/lib/kvsprintf.c
Labels: bug, or1k

#221 Fix gdb building error
  tools/dev/arch/setup-toolchain-i386.sh
  tools/dev/arch/setup-toolchain-or1k.sh
Labels: bug

#226 libm added to sbin and ubin build
  src/lib/makefile
  src/sbin/makefile
  src/ubin/makefile
Labels: enhancement, or1k
