Repository nanvix/nanvix, pull requests merged in 2025-01, with the labels that each got.

#440 [libs] F: implemented getpid syscall in Rust backend
  README.md
  doc/dev.md
  src/benchmarks/linux-app/src/main.rs
  src/libs/posix/src/unistd/bindings.rs
  src/libs/posix/src/unistd/mod.rs
  src/libs/posix/src/unistd/syscall/close.rs
  src/libs/posix/src/unistd/syscall/fchmod.rs
  src/libs/posix/src/unistd/syscall/fchown.rs
  src/libs/posix/src/unistd/syscall/fdatasync.rs
  src/libs/posix/src/unistd/syscall/fsync.rs
  src/libs/posix/src/unistd/syscall/ftruncate.rs
  src/libs/posix/src/unistd/syscall/getpid.rs
  src/libs/posix/src/unistd/syscall/linkat.rs
  src/libs/posix/src/unistd/syscall/lseek.rs
  src/libs/posix/src/unistd/syscall/mod.rs
  src/libs/posix/src/unistd/syscall/pread.rs
  src/libs/posix/src/unistd/syscall/pwrite.rs
  src/libs/posix/src/unistd/syscall/read.rs
  src/libs/posix/src/unistd/syscall/write.rs
Labels: feature

#441 [libs] E: creates config crate
  Cargo.toml
  build/kernel_config.toml
  build/scripts/run.sh
  build/scripts/setup/arch.sh
  build/scripts/setup/qemu.sh
  src/daemons/linuxd/Cargo.toml
  src/daemons/linuxd/src/main.rs
  src/kernel/Cargo.toml
  src/kernel/src/hal/mem/types/address/phys.rs
  src/kernel/src/hal/platform/hyperlight/mod.rs
  src/kernel/src/hal/platform/microvm.rs
  src/kernel/src/hal/platform/pc/mod.rs
  src/kernel/src/hal/platform/pc/qemu/mod.rs
  src/kernel/src/hal/platform/pc/qemu/pc.rs
  src/kernel/src/kcall/handler.rs
  src/kernel/src/kimage.rs
  src/kernel/src/mm/kheap.rs
  src/kernel/src/mm/kstack.rs
  src/kernel/src/mm/mod.rs
  src/kernel/src/mm/phys/frame.rs
  src/kernel/src/mm/phys/mod.rs
  src/kernel/src/mm/virt/mod.rs
  src/kernel/src/pm/mod.rs
  src/kernel/src/pm/process/manager.rs
  src/libs/config/Cargo.toml
  src/libs/config/build
  src/libs/config/build.rs
  src/libs/config/src/constants.rs
  src/libs/config/src/lib.rs
  src/libs/nvx/Cargo.toml
  src/libs/nvx/src/mm/mod.rs
  src/libs/sys/Cargo.toml
  src/libs/sys/src/sys/config.rs
  src/libs/sys/src/sys/ipc/message.rs
  src/libs/sys/src/sys/mod.rs
  src/microvm/Cargo.toml
  src/microvm/src/args.rs
  src/microvm/src/config.rs
  src/microvm/src/main.rs
  src/microvm/src/vmm/microvm/config.rs
  src/microvm/src/vmm/microvm/kvm/emulator.rs
  src/microvm/src/vmm/microvm/kvm/vmem.rs
  src/microvm/src/vmm/microvm/microvm.rs
  src/microvm/src/vmm/microvm/mod.rs
  src/tests/testd/Cargo.toml
  src/tests/testd/src/mm/mod.rs
Labels: enhancement

#443 Added documentation for building with docker from issue #442
  doc/build.md
  doc/dev.md
Labels: documentation

#444 [user] Hello-World in Java Script
  Makefile
  src/user/Makefile
  src/user/hello-js/Makefile
  src/user/hello-js/index.js
Labels: feature
