Repository nanvix/nanvix, pull requests merged in 2025-06, with the labels that each got.

#566 [libs] Safe System Call Wrappers
  src/daemons/linuxd/src/fcntl.rs
  src/kernel/src/pm/process/manager/mod.rs
  src/kernel/src/pm/sync/condvar.rs
  src/kernel/src/pm/sync/mutex.rs
  src/kernel/src/pm/thread/mod.rs
  src/libs/sys/src/sys/time/mod.rs
  src/libs/syscall/src/dlfcn/syscall/dynlib.rs
  src/libs/syscall/src/fcntl/message/fcntl.rs
  src/libs/syscall/src/fcntl/mod.rs
  src/libs/syscall/src/fcntl/syscall/fcntl.rs
  src/libs/syscall/src/fcntl/syscall/mod.rs
  src/libs/syscall/src/fcntl/syscall/rename.rs
  src/libs/syscall/src/safe/file/file_control_request.rs
  src/libs/syscall/src/safe/file/file_descriptor_flags.rs
  src/libs/syscall/src/safe/file/file_status_flags.rs
  src/libs/syscall/src/safe/file/mod.rs
  src/libs/syscall/src/safe/file/regular.rs
  src/libs/syscall/src/safe/file/whence.rs
  src/libs/syscall/src/safe/fs/attributes.rs
  src/libs/syscall/src/safe/fs/file_type.rs
  src/libs/syscall/src/safe/fs/mod.rs
  src/libs/syscall/src/safe/fs/path.rs
  src/libs/syscall/src/safe/fs/permissions.rs
  src/libs/syscall/src/safe/mod.rs
  src/libs/syscall/src/safe/sys/mod.rs
  src/libs/syscall/src/safe/time.rs
  src/libs/syscall/src/sys/stat/mod.rs
  src/libs/syscall/src/sys/stat/syscall/chmod.rs
  src/libs/syscall/src/sys/stat/syscall/mkdir.rs
  src/libs/syscall/src/sys/stat/syscall/mod.rs
  src/libs/syscall/src/unistd/mod.rs
  src/libs/syscall/src/unistd/syscall/mod.rs
  src/libs/syscall/src/unistd/syscall/readlink.rs
  src/libs/syscomm/src/lib.rs
  src/tests/file-rust/src/safe/file/allocate.rs
  src/tests/file-rust/src/safe/file/attributes.rs
  src/tests/file-rust/src/safe/file/seek.rs
  src/tests/file-rust/src/safe/file/sync.rs
  src/tests/file-rust/src/safe/file/write_read.rs
  src/tests/file-rust/src/safe/fs/create_remove.rs
  src/tests/file-rust/src/safe/fs/get_file_attributes.rs
  src/tests/file-rust/src/safe/fs/open_unlink.rs
Labels: feature

#569 [scripts] Improving Test Scripts
  Makefile
  scripts/test-linuxd.sh
  scripts/test-nanvixd.sh
Labels: enhancement

#577 [contrib] Updating Dependencies
  Cargo.toml
Labels: enhancement

#579 [kernel] Remove Process from Sleeping Queue
  Makefile
  scripts/ci.py
  scripts/pipeline.sh
  src/kernel/src/pm/sync/condvar.rs
Labels: bug

#580 [kernel] Switch Threads of Same Process
  src/kernel/src/pm/process/manager/mod.rs
Labels: bug

#585 [kernel] Drop Join CondVar when Exiting Thread
  src/kernel/src/pm/process/manager/unsafe.rs
  src/kernel/src/pm/thread/mod.rs
Labels: bug

#582 [ci] FIx slow and unintended behaviour of python-lint
  .githooks/post-commit
  .gitignore
  Makefile
Labels: bug

#598 [daemons] Use `eprint` for Writes to Standard Error
  src/daemons/linuxd/src/linuxd/mod.rs
Labels: bug

#610 [scripts] Fix GCC build and Rust Toolchain Setup
  scripts/setup/gcc.sh
  scripts/setup/rust.sh
Labels: bug

#609 [utils] Add `warm-start-vmm` Benchmark to `nanvix-bench`
  Cargo.toml
  doc/benchmark.md
  src/microvm/src/io.rs
  src/microvm/src/vmm/microvm/mod.rs
  src/utils/nanvix-bench/Cargo.toml
  src/utils/nanvix-bench/src/benchmark.rs
  src/utils/nanvix-bench/src/main.rs
Labels: feature

#617 [libs] Refactor `sysapi` Crate
  src/daemons/linuxd/src/dirent.rs
  src/daemons/linuxd/src/fcntl.rs
  src/libs/posix/src/pthread/mutex.rs
  src/libs/posix/src/sys/resource.rs
  src/libs/sysapi/src/dirent.rs
  src/libs/sysapi/src/lib.rs
  src/libs/sysapi/src/netinet_in.rs
  src/libs/sysapi/src/pthread.rs
  src/libs/sysapi/src/sys_resource.rs
  src/libs/sysapi/src/sys_stat.rs
  src/libs/sysapi/src/time.rs
  src/libs/syscall/src/dirent/mod.rs
  src/libs/syscall/src/pthread/syscall/cond.rs
  src/libs/syscall/src/pthread/syscall/mod.rs
  src/libs/syscall/src/pthread/syscall/mutex.rs
  src/libs/syscall/src/safe/fs/permissions.rs
  src/libs/syscall/src/sys/mod.rs
  src/libs/syscall/src/time/syscall/clock_getres.rs
  src/libs/syscall/src/time/syscall/clock_gettime.rs
  src/tests/file-rust/src/unsafe/file/fallocate.rs
  src/tests/file-rust/src/unsafe/file/fsync.rs
  src/tests/file-rust/src/unsafe/file/lseek.rs
  src/tests/file-rust/src/unsafe/file/pwrite_pread.rs
  src/tests/file-rust/src/unsafe/file/write_read.rs
  src/tests/file-rust/src/unsafe/fs/creat_unlink.rs
  src/tests/file-rust/src/unsafe/fs/open_unlink.rs
  src/tests/linux-app/src/file_system.rs
Labels: enhancement

#619 [libs] Renaming libs `size_t` and `ssize_t`
  src/benchmarks/echo-rust-nostd/src/main.rs
  src/benchmarks/echo-rust-server-nostd/src/main.rs
  src/benchmarks/echo-single-rust-nostd/src/main.rs
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/socket.rs
  src/daemons/linuxd/src/unistd.rs
  src/libs/posix/src/netdb.rs
  src/libs/posix/src/pthread/mod.rs
  src/libs/posix/src/sys/socket/mod.rs
  src/libs/posix/src/sys/uio/mod.rs
  src/libs/posix/src/unistd/mod.rs
  src/libs/sysapi/src/limits.rs
  src/libs/sysapi/src/sys_types.rs
  src/libs/sysapi/src/sys_uio.rs
  src/libs/syscall/src/dirent/message/getdents.rs
  src/libs/syscall/src/safe/fs/mod.rs
  src/libs/syscall/src/sys/socket/message/recv.rs
  src/libs/syscall/src/sys/socket/message/send.rs
  src/libs/syscall/src/sys/socket/syscall/send.rs
  src/libs/syscall/src/unistd/message/pread.rs
  src/libs/syscall/src/unistd/message/pwrite.rs
  src/libs/syscall/src/unistd/message/read.rs
  src/libs/syscall/src/unistd/message/write.rs
  src/libs/syscall/src/unistd/syscall/pread.rs
  src/libs/syscall/src/unistd/syscall/pwrite.rs
  src/libs/syscall/src/unistd/syscall/read.rs
  src/libs/syscall/src/unistd/syscall/readlink.rs
  src/libs/syscall/src/unistd/syscall/readlinkat.rs
  src/libs/syscall/src/unistd/syscall/write.rs
  src/tests/file-rust/src/unsafe/file/lseek.rs
Labels: enhancement

#620 [libs] Refactor `iovec` Structure
  src/libs/posix/src/sys/uio/mod.rs
  src/libs/sysapi/src/sys_types.rs
  src/libs/sysapi/src/sys_uio.rs
Labels: enhancement

#621 [libs] Update Signatures
  src/libs/posix/src/sys/socket/mod.rs
  src/libs/posix/src/sys/time/utimes.rs
  src/libs/posix/src/unistd/mod.rs
  src/libs/sysapi/src/errno.rs
  src/libs/sysapi/src/sys_select.rs
  src/libs/sysapi/src/sys_socket.rs
  src/libs/sysapi/src/unistd.rs
Labels: enhancement

#623 [libs] Improving Tracing for Pipe
  src/daemons/linuxd/src/main.rs
  src/libs/syscall/src/unistd/syscall/pipe.rs
Labels: enhancement

#629 [scripts] Updating Python Build Script
  scripts/build-python.sh
  scripts/setup/python.sh
  scripts/setup/toolchain.sh
Labels: bug

#631 [libs] Safe Conversions for Process Identifier
  src/kernel/src/kcall/mod.rs
  src/kernel/src/pm/kcall/mcopy.rs
  src/kernel/src/pm/kcall/mctrl.rs
  src/kernel/src/pm/kcall/mmap.rs
  src/kernel/src/pm/kcall/munmap.rs
  src/kernel/src/pm/kcall/terminate.rs
  src/kernel/src/pm/process/manager/mod.rs
  src/kernel/src/pm/process/manager/unsafe.rs
  src/libs/proc/src/daemon/mod.rs
  src/libs/sys/src/sys/kcall/mm/kcalls.rs
  src/libs/sys/src/sys/kcall/pm.rs
  src/libs/sys/src/sys/pm/pid.rs
Labels: enhancement

#634 [daemons] Bad Mask for fcntl()
  src/daemons/linuxd/src/fcntl.rs
Labels: enhancement
