Repository nanvix/nanvix, pull requests merged in 2025-10, with the labels that each got.

#1035 [libs] Dummy System Call Implementations
  src/libs/posix/src/dummy.rs
  src/libs/posix/src/lib.rs
Labels: feature

#1036 [libs] `malloc_usable_size()`
  src/libs/libc_stdlib/Cargo.toml
  src/libs/libc_stdlib/src/block_header.rs
  src/libs/libc_stdlib/src/lib.rs
  src/libs/libc_stdlib/src/malloc_usable_size.rs
  src/tests/memory-c/common.h
  src/tests/memory-c/main.c
  src/tests/memory-c/malloc_usable_size.c
Labels: feature

#1038 [tests] Adding QuickJS To CI
  Makefile
Labels: feature

#1015 [microvm] Load virtual memory snapshots
  src/microvm/src/orchestrator.rs
  src/microvm/src/vmm/hyperlight/mod.rs
  src/microvm/src/vmm/microvm/kvm/vcpu/mod.rs
  src/microvm/src/vmm/microvm/kvm/vmem.rs
  src/microvm/src/vmm/microvm/microvm.rs
  src/microvm/src/vmm/microvm/mod.rs
Labels: feature

#1041 [build] Fix Cleanup Command
  Makefile
  scripts/build-opt.sh
  z
Labels: bug

#1044 [libs] Asynchronous Wrapper of Syscomm Library
  src/libs/syscomm/Cargo.toml
  src/libs/syscomm/src/async.rs
  src/libs/syscomm/src/lib.rs
  src/utils/nanvixd/Cargo.toml
  src/utils/nanvixd/src/cache/mod.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
  src/utils/nanvixd/src/sandbox/microvm.rs
Labels: enhancement
