Repository nanvix/nanvix, pull requests merged in 2025-07, with the labels that each got.

#642 [libs] Support Out of Order Message Part Processing
  src/daemons/linuxd/src/linuxd/mod.rs
  src/libs/syscall/src/dirent/message/getdents.rs
  src/libs/syscall/src/fcntl/message/openat.rs
  src/libs/syscall/src/fcntl/message/renameat.rs
  src/libs/syscall/src/fcntl/message/unlinkat.rs
  src/libs/syscall/src/fcntl/syscall/openat.rs
  src/libs/syscall/src/fcntl/syscall/renameat.rs
  src/libs/syscall/src/fcntl/syscall/unlinkat.rs
  src/libs/syscall/src/lib.rs
  src/libs/syscall/src/message/long.rs
  src/libs/syscall/src/message/mod.rs
  src/libs/syscall/src/message/part.rs
  src/libs/syscall/src/sys/stat/message/fchmodat.rs
  src/libs/syscall/src/sys/stat/message/fstatat.rs
  src/libs/syscall/src/sys/stat/message/mkdirat.rs
  src/libs/syscall/src/sys/stat/message/utimensat.rs
  src/libs/syscall/src/sys/stat/syscall/fchmodat.rs
  src/libs/syscall/src/sys/stat/syscall/fstatat.rs
  src/libs/syscall/src/sys/stat/syscall/mkdirat.rs
  src/libs/syscall/src/sys/stat/syscall/utimensat.rs
  src/libs/syscall/src/unistd/message/chdir.rs
  src/libs/syscall/src/unistd/message/faccessat.rs
  src/libs/syscall/src/unistd/message/fchownat.rs
  src/libs/syscall/src/unistd/message/getcwd.rs
  src/libs/syscall/src/unistd/message/linkat.rs
  src/libs/syscall/src/unistd/message/readlinkat.rs
  src/libs/syscall/src/unistd/message/symlinkat.rs
  src/libs/syscall/src/unistd/syscall/chdir.rs
  src/libs/syscall/src/unistd/syscall/fchownat.rs
  src/libs/syscall/src/unistd/syscall/linkat.rs
  src/libs/syscall/src/unistd/syscall/readlinkat.rs
  src/libs/syscall/src/unistd/syscall/symlinkat.rs
Labels: enhancement

#647 [scripts] VSCode Settings Template
  doc/setup.md
  scripts/setup/vscode/settings.json
Labels: feature

#649 [scripts] Fix In Source Tree Detection
  doc/setup.md
  scripts/setup/rust.sh
Labels: bug

#651 [ci] Speeding Up
  Makefile
  scripts/ci.py
Labels: enhancement

#654 [llibs] Moving `fcntl` System Calls
  src/libs/posix/src/fcntl/mod.rs
  src/libs/posix/src/lib.rs
  src/libs/sysapi/src/fcntl.rs
  src/libs/syscall/src/fcntl/bindings/mod.rs
  src/libs/syscall/src/fcntl/bindings/open.rs
  src/libs/syscall/src/fcntl/bindings/posix_fadvise.rs
  src/libs/syscall/src/fcntl/bindings/posix_fallocate.rs
  src/libs/syscall/src/fcntl/bindings/renameat.rs
  src/libs/syscall/src/fcntl/bindings/unlinkat.rs
Labels: enhancement

#656 [kernel] Fix System Time Calculation
  src/kernel/src/pm/clock.rs
Labels: bug

#657 [daemons] Improving Performance of `linuxd`
  src/daemons/linuxd/src/linuxd/mod.rs
Labels: enhancement

#662 [kernel] Fix Kernel Scheduler
  build/kernel_config.toml
  src/kernel/src/kcall/dispatcher.rs
  src/kernel/src/kcall/handler.rs
  src/kernel/src/pm/clock.rs
  src/kernel/src/pm/mod.rs
  src/kernel/src/pm/process/manager/mod.rs
  src/kernel/src/pm/process/manager/unsafe.rs
  src/kernel/src/pm/process/state/interrupted.rs
  src/kernel/src/pm/process/state/runnable.rs
  src/kernel/src/pm/process/state/running.rs
  src/kernel/src/pm/process/state/sleeping.rs
  src/kernel/src/pm/thread/mod.rs
Labels: bug

#669 [libs] Moving `socket` System Calls to `syscall` Crate
  src/libs/posix/src/sys/mod.rs
  src/libs/posix/src/sys/socket/mod.rs
  src/libs/syscall/src/netinet/in_.rs
  src/libs/syscall/src/sys/socket/bindings/accept.rs
  src/libs/syscall/src/sys/socket/bindings/bind.rs
  src/libs/syscall/src/sys/socket/bindings/connect.rs
  src/libs/syscall/src/sys/socket/bindings/getpeername.rs
  src/libs/syscall/src/sys/socket/bindings/getsockname.rs
  src/libs/syscall/src/sys/socket/bindings/getsockopt.rs
  src/libs/syscall/src/sys/socket/bindings/listen.rs
  src/libs/syscall/src/sys/socket/bindings/mod.rs
  src/libs/syscall/src/sys/socket/bindings/recv.rs
  src/libs/syscall/src/sys/socket/bindings/recvfrom.rs
  src/libs/syscall/src/sys/socket/bindings/recvmsg.rs
  src/libs/syscall/src/sys/socket/bindings/send.rs
  src/libs/syscall/src/sys/socket/bindings/sendmsg.rs
  src/libs/syscall/src/sys/socket/bindings/sendto.rs
  src/libs/syscall/src/sys/socket/bindings/setsockopt.rs
  src/libs/syscall/src/sys/socket/bindings/shutdown.rs
  src/libs/syscall/src/sys/socket/bindings/socket.rs
  src/libs/syscall/src/sys/socket/bindings/socketpair.rs
  src/libs/syscall/src/sys/socket/mod.rs
Labels: enhancement

#673 [utils] Remove Hard-Coded Core-Pinning in `nanvix-bench`
  doc/benchmark.md
  src/utils/nanvix-bench/Cargo.toml
  src/utils/nanvix-bench/src/args.rs
  src/utils/nanvix-bench/src/benchmark.rs
  src/utils/nanvix-bench/src/hwloc.rs
  src/utils/nanvix-bench/src/main.rs
Labels: bug

#675 [scripts] B: Missing WASI_SDK_PATH
  scripts/setup/rust.sh
Labels: bug

#681 [scripts] Increase Timeout in test-nanvixd.sh
  scripts/test-nanvixd.sh
Labels: enhancement

#679 [libs] Missing Binding for __errno_location()
  src/libs/syscall/src/errno.rs
Labels: bug

#683 [ci] Set hwloc.json for Benchmarks
  .github/actions/benchmark/action.yml
Labels: enhancement

#685 [kernel] Performance Counters
  src/kernel/src/hal/platform/hyperlight/mod.rs
  src/kernel/src/hal/platform/microvm.rs
  src/kernel/src/kmain.rs
  src/kernel/src/pm/clock.rs
  src/kernel/src/pm/mod.rs
  src/kernel/src/pm/process/manager/unsafe.rs
Labels: enhancement

#687 [kernel] Poll Batch of IKC Messages
  build/kernel_config.toml
  src/kernel/src/kcall/handler.rs
  src/libs/config/build.rs
Labels: enhancement

#688 [libs] Moving `unistd` System Call Bindings
  src/libs/error/src/lib.rs
  src/libs/posix/src/lib.rs
  src/libs/posix/src/unistd/mod.rs
  src/libs/syscall/src/unistd/bindings/_exit.rs
  src/libs/syscall/src/unistd/bindings/access.rs
  src/libs/syscall/src/unistd/bindings/chdir.rs
  src/libs/syscall/src/unistd/bindings/chown.rs
  src/libs/syscall/src/unistd/bindings/chroot.rs
  src/libs/syscall/src/unistd/bindings/dup.rs
  src/libs/syscall/src/unistd/bindings/dup2.rs
  src/libs/syscall/src/unistd/bindings/execv.rs
  src/libs/syscall/src/unistd/bindings/execve.rs
  src/libs/syscall/src/unistd/bindings/faccessat.rs
  src/libs/syscall/src/unistd/bindings/fchdir.rs
  src/libs/syscall/src/unistd/bindings/fchown.rs
  src/libs/syscall/src/unistd/bindings/fchownat.rs
  src/libs/syscall/src/unistd/bindings/fdatasync.rs
  src/libs/syscall/src/unistd/bindings/fork.rs
  src/libs/syscall/src/unistd/bindings/fsync.rs
  src/libs/syscall/src/unistd/bindings/ftruncate.rs
  src/libs/syscall/src/unistd/bindings/getcwd.rs
  src/libs/syscall/src/unistd/bindings/getegid.rs
  src/libs/syscall/src/unistd/bindings/getentropy.rs
  src/libs/syscall/src/unistd/bindings/geteuid.rs
  src/libs/syscall/src/unistd/bindings/getgid.rs
  src/libs/syscall/src/unistd/bindings/gethostname.rs
  src/libs/syscall/src/unistd/bindings/getpid.rs
  src/libs/syscall/src/unistd/bindings/getuid.rs
  src/libs/syscall/src/unistd/bindings/isatty.rs
  src/libs/syscall/src/unistd/bindings/lchown.rs
  src/libs/syscall/src/unistd/bindings/link.rs
  src/libs/syscall/src/unistd/bindings/linkat.rs
  src/libs/syscall/src/unistd/bindings/lseek.rs
  src/libs/syscall/src/unistd/bindings/mod.rs
  src/libs/syscall/src/unistd/bindings/pread.rs
  src/libs/syscall/src/unistd/bindings/pwrite.rs
  src/libs/syscall/src/unistd/bindings/read.rs
  src/libs/syscall/src/unistd/bindings/readlink.rs
  src/libs/syscall/src/unistd/bindings/readlinkat.rs
  src/libs/syscall/src/unistd/bindings/rmdir.rs
  src/libs/syscall/src/unistd/bindings/sbrk.rs
  src/libs/syscall/src/unistd/bindings/setegid.rs
  src/libs/syscall/src/unistd/bindings/seteuid.rs
  src/libs/syscall/src/unistd/bindings/setgid.rs
  src/libs/syscall/src/unistd/bindings/setgroups.rs
  src/libs/syscall/src/unistd/bindings/setuid.rs
  src/libs/syscall/src/unistd/bindings/sleep.rs
  src/libs/syscall/src/unistd/bindings/symlink.rs
  src/libs/syscall/src/unistd/bindings/symlinkat.rs
  src/libs/syscall/src/unistd/bindings/sysconf.rs
  src/libs/syscall/src/unistd/bindings/unlink.rs
  src/libs/syscall/src/unistd/bindings/waitpid.rs
  src/libs/syscall/src/unistd/bindings/write.rs
  src/libs/syscall/src/unistd/mod.rs
Labels: enhancement

#690 [microvm] Sets up plumbing for snapshots
  src/microvm/src/lib.rs
  src/microvm/src/main.rs
  src/microvm/src/vmm/hyperlight/io.rs
  src/microvm/src/vmm/hyperlight/mod.rs
  src/microvm/src/vmm/microvm/io.rs
  src/microvm/src/vmm/microvm/mod.rs
  src/utils/nanvix-bench/src/main.rs
Labels: feature

#702 [ci] Add Tags To Self-Hosted Runners
  .github/workflows/self-hosted-ci.yml
Labels: enhancement

#708 [ci] Run on Non-Draft PR Branches from Copilot
  .github/actions/benchmark/action.yml
  .github/workflows/self-hosted-ci.yml
Labels: bug

#698 [utils] Refactor Nanvixd To Act As Unified Control-Plane
  Cargo.toml
  Makefile
  doc/nanvixd.md
  scripts/ci.py
  scripts/setup/ubuntu.sh
  scripts/test-linuxd.sh
  scripts/test-nanvixd.sh
  src/benchmarks/echo-c/main.c
  src/benchmarks/echo-cpp/main.cpp
  src/benchmarks/echo-rust-nostd/src/main.rs
  src/benchmarks/echo-rust-server-nostd/Cargo.toml
  src/benchmarks/echo-rust-server-nostd/build
  src/benchmarks/echo-rust-server-nostd/build.rs
  src/benchmarks/echo-rust-server-nostd/src/main.rs
  src/benchmarks/echo-single-rust-nostd/Cargo.toml
  src/benchmarks/echo-single-rust-nostd/build
  src/benchmarks/echo-single-rust-nostd/build.rs
  src/benchmarks/echo-single-rust-nostd/src/main.rs
  src/benchmarks/echo-wasm-rust/src/main.rs
  src/daemons/linuxd/src/args.rs
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/main.rs
  src/daemons/linuxd/src/venv.rs
  src/libs/syscomm/src/lib.rs
  src/utils/nanvix-bench/Cargo.toml
  src/utils/nanvix-bench/src/benchmark.rs
  src/utils/nanvix-bench/src/env.rs
  src/utils/nanvix-bench/src/main.rs
  src/utils/nanvixd/Cargo.toml
  src/utils/nanvixd/src/args.rs
  src/utils/nanvixd/src/cache/handle.rs
  src/utils/nanvixd/src/cache/mod.rs
  src/utils/nanvixd/src/config.rs
  src/utils/nanvixd/src/http.rs
  src/utils/nanvixd/src/lib.rs
  src/utils/nanvixd/src/main.rs
  src/utils/nanvixd/src/message.rs
  src/utils/nanvixd/src/sandbox/config.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
  src/utils/nanvixd/src/sandbox/microvm.rs
  src/utils/nanvixd/src/sandbox/mod.rs
  src/utils/nanvixd/src/sandbox/tag.rs
Labels: enhancement
