Repository nanvix/nanvix, pull requests merged in 2025-08, with the labels that each got.

#729 [scripts] Automate Docker Image Creation for Nanvix
  scripts/setup/Dockerfile
  scripts/setup/docker.sh
Labels: feature

#738 [scripts] Improve Randomness on Unix Socket Names
  scripts/test-nanvixd.sh
  src/utils/nanvix-bench/src/main.rs
  src/utils/nanvixd/src/config.rs
  src/utils/nanvixd/src/http.rs
  src/utils/nanvixd/src/sandbox/tag.rs
Labels: bug

#739 [scripts] Fix Minor Issues in `test-nanvix.sh`
  scripts/test-nanvixd.sh
Labels: bug

#741 [daemons] Support Graceful Interruption of Linuxd Worker Threads
  src/daemons/linuxd/src/dirent.rs
  src/daemons/linuxd/src/error.rs
  src/daemons/linuxd/src/fcntl.rs
  src/daemons/linuxd/src/linuxd/assemble.rs
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/main.rs
  src/daemons/linuxd/src/message.rs
  src/daemons/linuxd/src/poll.rs
  src/daemons/linuxd/src/socket.rs
  src/daemons/linuxd/src/times.rs
  src/daemons/linuxd/src/unistd.rs
  src/daemons/linuxd/src/venv.rs
  src/daemons/linuxd/src/worker_thread.rs
  src/libs/syscomm/src/lib.rs
Labels: feature

#742 [build] `z` Utility
  .gitignore
  doc/build.md
  z
Labels: feature

#748 [ci] Empowering GitHub Copilot
  .github/copilot-instructions.md
  .github/workflows/copilot-setup-steps.yml
Labels: feature

#743 [utils] Make Nanvixd Send Shutdown Messages To Linuxd
  src/libs/syscomm/src/lib.rs
  src/utils/nanvix-bench/src/main.rs
  src/utils/nanvixd/Cargo.toml
  src/utils/nanvixd/src/cache/mod.rs
  src/utils/nanvixd/src/control_plane.rs
  src/utils/nanvixd/src/lib.rs
  src/utils/nanvixd/src/main.rs
  src/utils/nanvixd/src/message.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
Labels: feature

#758 [daemons] Fix Build Warning in WASMD
  src/daemons/wasmd/src/engine/mod.rs
Labels: bug

#701 [microvm] Add states and transitions to MicroVM snapshotting protocol
  src/microvm/src/vmm/microvm/io.rs
  src/microvm/src/vmm/microvm/mod.rs
Labels: feature

#761 [ci] Coding Standards and Review Guidelines for Copilot
  .github/copilot-instructions.md
Labels: enhancement

#763 [devops] Enforce Code Formatting
  .githooks/pre-commit
  .github/actions/format/action.yml
  .github/copilot-instructions.md
  .github/workflows/self-hosted-ci.yml
  Makefile
  scripts/ci.py
  z
Labels: enhancement

#771 [build] Enforce Cleanup When Switching Build Modes
  Makefile
  z
Labels: bug

#768 [devops] Enforce Code Linting Rules
  .githooks/post-commit
  .githooks/pre-commit
  .github/copilot-instructions.md
  Makefile
  scripts/ci.py
Labels: enhancement

#770 [daemons] User VM Handle
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/main.rs
  src/daemons/linuxd/src/user_vm_handle.rs
  src/daemons/linuxd/src/venv.rs
  src/daemons/linuxd/src/worker_thread.rs
Labels: enhancement

#775 [git] Fix Pre-Commit z Checks In Non-Docker Builds
  .githooks/pre-commit
Labels: bug

#774 [libs] Move Syscomm To Metal IO Sockets
  Cargo.toml
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/main.rs
  src/daemons/linuxd/src/user_vm_handle.rs
  src/daemons/linuxd/src/worker_thread.rs
  src/libs/config/src/lib.rs
  src/libs/syscomm/Cargo.toml
  src/libs/syscomm/src/lib.rs
  src/microvm/src/gateway.rs
  src/microvm/src/main.rs
  src/utils/nanvix-bench/Cargo.toml
  src/utils/nanvix-bench/src/main.rs
  src/utils/nanvixd/src/control_plane.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
Labels: feature

#793 [daemons] Make Linuxd Poll Over A Single Connection + Control-Plane Socket
  src/daemons/linuxd/Cargo.toml
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/main.rs
  src/utils/nanvixd/src/control_plane.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
Labels: enhancement

#785 [libs] E: Moving `signal` Module to `syscall` Crate
  src/libs/posix/src/lib.rs
  src/libs/syscall/Cargo.toml
  src/libs/syscall/src/lib.rs
  src/libs/syscall/src/signal/bindings/kill.rs
  src/libs/syscall/src/signal/bindings/mod.rs
  src/libs/syscall/src/signal/bindings/sigaction.rs
  src/libs/syscall/src/signal/mod.rs
Labels: enhancement

#800 [microvm] Tolerate Race When Connecting To System VM
  src/libs/syscomm/src/lib.rs
  src/microvm/src/main.rs
Labels: bug

#801 [libs] Improving `MemorySegment` Abstraction
  src/libs/syscall/Cargo.toml
  src/libs/syscall/src/dlfcn/syscall/dynlib.rs
  src/libs/syscall/src/dlfcn/syscall/mod.rs
  src/libs/syscall/src/safe/mem/mod.rs
  src/libs/syscall/src/safe/mem/segment.rs
  src/libs/syscall/src/safe/mod.rs
Labels: enhancement

#795 [microvm] Connect to Control Plane
  src/libs/config/src/lib.rs
  src/libs/syscomm/src/lib.rs
  src/microvm/src/args.rs
  src/microvm/src/main.rs
  src/utils/nanvixd/Cargo.toml
  src/utils/nanvixd/src/cache/mod.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
  src/utils/nanvixd/src/sandbox/microvm.rs
Labels: feature

#805 [ci] Fix PR Num Retrieval and Comment Posting
  .github/actions/benchmark/action.yml
Labels: bug

#806 [daemons] Make Linuxd Poll For Gateway Connections
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/main.rs
Labels: feature

#814 [daemons] Linuxd Mangages Multiple User VMs
  Cargo.toml
  src/daemons/linuxd/Cargo.toml
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/main.rs
  src/daemons/linuxd/src/user_vm_handle.rs
Labels: feature

#815 [scripts] Update VS Code Settings
  scripts/setup/vscode/settings.json
Labels: enhancement

#816 [daemons] Drain Sockets On Every User VM Poll Notification
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/user_vm_handle.rs
  src/daemons/linuxd/src/worker_thread.rs
Labels: bug

#819 [utils] Add -tmp-dir To Nanvix-Bench For Nanvixd
  .github/actions/benchmark/action.yml
  src/utils/nanvix-bench/src/args.rs
  src/utils/nanvix-bench/src/benchmark.rs
  src/utils/nanvix-bench/src/main.rs
Labels: enhancement

#818 [microvm] Interrupt vCPU With Signal
  src/microvm/src/vmm/microvm/kvm/vcpu/exit.rs
  src/microvm/src/vmm/microvm/kvm/vcpu/mod.rs
  src/microvm/src/vmm/microvm/microvm.rs
  src/microvm/src/vmm/microvm/mod.rs
Labels: feature

#792 [ci] Updating Copilot Instructions
  .github/copilot-instructions.md
Labels: enhancement

#823 [kernel] Refactor `create_thread()` Kernel Call
  src/kernel/src/mm/virt/vmem.rs
  src/kernel/src/pm/kcall/create_thread.rs
  src/kernel/src/pm/process/manager/mod.rs
  src/libs/sys/src/sys/kcall/pm.rs
  src/libs/sys/src/sys/mm/address/virt.rs
  src/libs/sys/src/sys/pm/mod.rs
  src/libs/sys/src/sys/pm/thread_create_args.rs
Labels: enhancement

#827 [utils] Remove Sandbox ID From Socket Addresses
  src/utils/nanvixd/src/config.rs
  src/utils/nanvixd/src/http.rs
Labels: bug

#835 [ci] Group Updates on KVM Crates
  .github/dependabot.yml
Labels: bug

#834 [kernel] Handle Thread Stack Creation in User Space
  src/kernel/src/mm/ustack.rs
  src/kernel/src/pm/kcall/create_thread.rs
  src/kernel/src/pm/process/manager/mod.rs
  src/kernel/src/pm/process/state/mod.rs
  src/kernel/src/pm/process/state/runnable.rs
  src/libs/sys/src/sys/kcall/pm.rs
  src/libs/sys/src/sys/pm/thread_create_args.rs
  src/libs/syscall/src/pthread/syscall/cond.rs
  src/libs/syscall/src/pthread/syscall/mod.rs
  src/libs/syscall/src/pthread/syscall/mutex.rs
  src/libs/syscall/src/safe/mem/mod.rs
  src/libs/syscall/src/safe/mem/stack.rs
Labels: enhancement

#848 [kernel] Make GDT Global
  src/kernel/src/hal/arch/x86/cpu/mod.rs
  src/kernel/src/hal/arch/x86/mem/gdt.rs
  src/kernel/src/hal/arch/x86/mod.rs
  src/libs/arch/src/x86/mem/gdt.rs
Labels: enhancement

#851 [build] B: Remove Unnnecessary .gitmodules File
  .gitmodules
Labels: enhancement

#881 [scripts] Logging Script
  scripts/common/logging.sh
  scripts/create-minor-release.sh
  scripts/setup/docker.sh
  scripts/setup/toolchain.sh
  z
Labels: enhancement

#884 [scripts] Util Script
  scripts/common/utils.sh
  scripts/create-minor-release.sh
  scripts/setup/toolchain.sh
  z
Labels: enhancement

#888 [kernel] Refactor Thread Module
  src/kernel/src/pm/process/manager/mod.rs
  src/kernel/src/pm/process/state/interrupted.rs
  src/kernel/src/pm/process/state/runnable.rs
  src/kernel/src/pm/process/state/running.rs
  src/kernel/src/pm/process/state/sleeping.rs
  src/kernel/src/pm/process/state/zombie.rs
  src/kernel/src/pm/thread/interrupted.rs
  src/kernel/src/pm/thread/mod.rs
  src/kernel/src/pm/thread/ready.rs
  src/kernel/src/pm/thread/running.rs
  src/kernel/src/pm/thread/sleeping.rs
  src/kernel/src/pm/thread/state.rs
  src/kernel/src/pm/thread/zombie.rs
Labels: enhancement

#894 [kernel] Zero Out Regs Before Jump to User Mode
  src/kernel/src/hal/arch/x86/hooks.S
Labels: enhancement

#895 [build] Fix Code Formatting for Assembly Code
  scripts/setup/vscode/settings.json
  src/kernel/src/hal/arch/x86/hooks.S
Labels: bug

#896 [libs] Improve Conversions for Alignment Struct
  src/libs/sys/src/sys/mm/alignment.rs
Labels: enhancement

#899 [kernel] Initial Support for Thread Data Area
  build/user/linker/x86/user.ld
  src/kernel/src/hal/arch/x86/cpu/context.rs
  src/kernel/src/hal/arch/x86/cpu/interrupt/mod.rs
  src/kernel/src/hal/arch/x86/hooks.S
  src/kernel/src/hal/arch/x86/mem/gdt.rs
  src/kernel/src/kcall/handler.rs
  src/kernel/src/mm/elf.rs
  src/kernel/src/pm/kcall/create_thread.rs
  src/kernel/src/pm/kcall/get_thread_data_area.rs
  src/kernel/src/pm/kcall/mod.rs
  src/kernel/src/pm/kcall/set_thread_data_area.rs
  src/kernel/src/pm/process/manager/mod.rs
  src/kernel/src/pm/process/manager/unsafe.rs
  src/kernel/src/pm/process/state/runnable.rs
  src/kernel/src/pm/process/state/sleeping.rs
  src/kernel/src/pm/thread/mod.rs
  src/kernel/src/pm/thread/ready.rs
  src/kernel/src/pm/thread/sleeping.rs
  src/kernel/src/pm/thread/state.rs
  src/libs/nvx/src/lib.rs
  src/libs/sys/src/sys/kcall/pm.rs
  src/libs/sys/src/sys/mm/address/virt.rs
  src/libs/sys/src/sys/number.rs
  src/libs/sys/src/sys/pm/thread_create_args.rs
  src/libs/sysalloc/Cargo.toml
  src/libs/sysalloc/src/lib.rs
  src/libs/sysalloc/src/tda.rs
  src/libs/syscall/Cargo.toml
  src/libs/syscall/src/pthread/syscall/mod.rs
  src/tests/thread-c/common.h
  src/tests/thread-c/main.c
  src/tests/thread-c/thread_local.c
Labels: feature

#901 [build] Run Codespell on All Tracked Files
  .github/workflows/github-hosted-ci.yml
  Makefile
Labels: bug

#906 [libs] Add MXCRS Register Structure
  src/libs/arch/src/x86/cpu/mod.rs
  src/libs/arch/src/x86/cpu/mxcrs.rs
Labels: feature

#907 [libs] Preserve EBX Register in CPUID Function
  src/libs/arch/src/x86/cpu/cpuid.rs
Labels: bug

#908 [kernel] Initial FPU Support
  Makefile
  src/kernel/Cargo.toml
  src/kernel/src/hal/arch/x86/cpu/context.rs
  src/kernel/src/hal/arch/x86/cpu/fpu.rs
  src/kernel/src/hal/arch/x86/cpu/mod.rs
  src/kernel/src/hal/arch/x86/cpu/nofpu.rs
  src/kernel/src/hal/arch/x86/hooks.S
  src/kernel/src/pm/process/manager/mod.rs
  src/kernel/src/pm/process/manager/unsafe.rs
  src/kernel/src/pm/process/state/runnable.rs
  src/kernel/src/pm/process/state/running.rs
  src/kernel/src/pm/thread/mod.rs
  src/kernel/src/pm/thread/ready.rs
  src/kernel/src/pm/thread/running.rs
  src/kernel/src/pm/thread/state.rs
  src/microvm/Cargo.toml
  src/microvm/src/vmm/microvm/kvm/partition.rs
  src/microvm/src/vmm/microvm/kvm/vcpu/mod.rs
Labels: feature

#910 [libs] Encapsulate Logic To Create Build-Time Constants From TOML + Add Linuxd Config TOML
  build/linuxd_config.toml
  scripts/common/utils.sh
  scripts/generate-l2-initramfs.sh
  scripts/generate-l2-snapshot.sh
  src/libs/config/build.rs
Labels: enhancement
