Repository nanvix/nanvix, pull requests merged in 2025-09, with the labels that each got.

#919 [microvm] Collapses common code between microvm and hyperlight
  src/microvm/src/io_thread.rs
  src/microvm/src/lib.rs
  src/microvm/src/memory_thread.rs
  src/microvm/src/orchestrator.rs
  src/microvm/src/vmm/hyperlight/mod.rs
  src/microvm/src/vmm/microvm/io.rs
  src/microvm/src/vmm/microvm/mod.rs
Labels: enhancement

#925 [scripts] Use String Comparison for Error Code Check
  scripts/test-nanvixd.sh
Labels: bug

#924 [utils] Expose `-toolchain-bin-dir` To Nanvixd
  .github/actions/benchmark/action.yml
  scripts/test-nanvixd.sh
  src/utils/nanvix-bench/src/args.rs
  src/utils/nanvix-bench/src/benchmark.rs
  src/utils/nanvix-bench/src/main.rs
  src/utils/nanvixd/src/args.rs
  src/utils/nanvixd/src/cache/mod.rs
  src/utils/nanvixd/src/config.rs
  src/utils/nanvixd/src/http.rs
  src/utils/nanvixd/src/main.rs
  src/utils/nanvixd/src/sandbox/config.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
Labels: enhancement

#923 [ci] Test MicroVM with Experimental Features
  .github/actions/build/action.yml
  .github/actions/test/action.yml
  Makefile
  scripts/ci.py
Labels: feature

#920 [daemons] Homogeneous User VM Identifiers
  Cargo.toml
  Makefile
  doc/run.md
  scripts/test-nanvixd.sh
  src/daemons/linuxd/Cargo.toml
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/user_vm_handle.rs
  src/daemons/linuxd/src/venv.rs
  src/libs/config/src/lib.rs
  src/libs/syscomm/src/lib.rs
  src/libs/user-vm-api/Cargo.toml
  src/libs/user-vm-api/src/lib.rs
  src/microvm/Cargo.toml
  src/microvm/src/args.rs
  src/microvm/src/main.rs
  src/utils/nanvix-bench/Cargo.toml
  src/utils/nanvix-bench/src/main.rs
  src/utils/nanvixd/Cargo.toml
  src/utils/nanvixd/src/cache/mod.rs
  src/utils/nanvixd/src/http.rs
  src/utils/nanvixd/src/message.rs
  src/utils/nanvixd/src/sandbox/microvm.rs
  src/utils/nanvixd/src/sandbox/tag.rs
Labels: enhancement

#843 [daemons] Support Linuxd Deployment in L2 VM
  .github/actions/benchmark/action.yml
  .github/workflows/self-hosted-benchmark.yml
  .github/workflows/self-hosted-ci.yml
  Makefile
  build/linuxd_config.toml
  scripts/generate-l2-initramfs.sh
  scripts/generate-l2-snapshot.sh
  scripts/setup/Dockerfile
  scripts/setup/ubuntu.sh
  src/daemons/linuxd/src/args.rs
  src/daemons/linuxd/src/config.rs
  src/daemons/linuxd/src/lib.rs
  src/daemons/linuxd/src/linuxd/mod.rs
  src/daemons/linuxd/src/main.rs
  src/libs/config/build.rs
  src/libs/config/src/lib.rs
  src/utils/nanvix-bench/src/args.rs
  src/utils/nanvix-bench/src/benchmark.rs
  src/utils/nanvix-bench/src/main.rs
  src/utils/nanvixd/src/args.rs
  src/utils/nanvixd/src/cache/mod.rs
  src/utils/nanvixd/src/config.rs
  src/utils/nanvixd/src/http.rs
  src/utils/nanvixd/src/sandbox/config.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
  src/utils/nanvixd/src/sandbox/microvm.rs
Labels: feature

#927 [utils] Log linuxd Output to a File
  src/utils/nanvixd/src/sandbox/linuxd.rs
Labels: bug

#928 [scripts] Log Program's Output to a File
  scripts/test-nanvixd.sh
Labels: bug

#931 [libs] Improving Thread Attributes Object Initialization / Destruction
  src/libs/syscall/src/pthread/bindings/pthread_attr_destroy.rs
  src/libs/syscall/src/pthread/bindings/pthread_attr_init.rs
  src/libs/syscall/src/pthread/mod.rs
  src/libs/syscall/src/pthread/syscall/mod.rs
  src/libs/syscall/src/pthread/syscall/pthread_attr_destroy.rs
  src/libs/syscall/src/pthread/syscall/pthread_attr_init.rs
  src/tests/thread-c/attr_init_destroy.c
  src/tests/thread-c/common.h
  src/tests/thread-c/main.c
Labels: enhancement

#938 [ci] Disabling Benchmarks with L2 VM
  .github/actions/benchmark/action.yml
Labels: enhancement

#940 [scripts] Missing SCRIPTS_DIR in toolchain.sh
  scripts/setup/toolchain.sh
Labels: bug

#941 [libs] Global ARGC/ARGV in `nvx` Crate
  src/libs/nvx/src/lib.rs
Labels: enhancement

#944 [libs] Initial Implementation for `pthread_attr_getstack()`
  src/libs/posix/src/pthread/mod.rs
  src/libs/syscall/src/pthread/bindings/mod.rs
  src/libs/syscall/src/pthread/bindings/pthread_attr_getstack.rs
  src/libs/syscall/src/pthread/syscall/mod.rs
  src/libs/syscall/src/pthread/syscall/pthread_attr_getstack.rs
  src/tests/thread-c/common.h
  src/tests/thread-c/getstack.c
  src/tests/thread-c/main.c
Labels: feature

#922 [microvm] Adds infrastructure for pause-resume functionality
  src/microvm/src/io_thread.rs
  src/microvm/src/memory_thread.rs
  src/microvm/src/orchestrator.rs
  src/microvm/src/vmm/hyperlight/mod.rs
  src/microvm/src/vmm/microvm/microvm.rs
  src/microvm/src/vmm/microvm/mod.rs
Labels: feature

#856 [microvm] Add pause and resume functionality
  src/kernel/src/pm/clock.rs
  src/libs/config/src/lib.rs
  src/microvm/src/orchestrator.rs
  src/microvm/src/vmm/microvm/kvm/emulator.rs
  src/microvm/src/vmm/microvm/microvm.rs
  src/microvm/src/vmm/microvm/mod.rs
Labels: feature

#953 [build] Drop SSE Feature
  .github/actions/build/action.yml
  .github/actions/test/action.yml
  Makefile
  scripts/run.sh
  src/kernel/Cargo.toml
  src/kernel/src/event/manager.rs
  src/kernel/src/hal/arch/mod.rs
  src/kernel/src/hal/arch/x86/cpu/context.rs
  src/kernel/src/hal/arch/x86/cpu/mod.rs
  src/kernel/src/hal/arch/x86/cpu/nofpu.rs
  src/kernel/src/hal/arch/x86/mod.rs
  src/kernel/src/pm/process/manager/mod.rs
  src/kernel/src/pm/process/manager/unsafe.rs
  src/kernel/src/pm/process/state/interrupted.rs
  src/kernel/src/pm/process/state/runnable.rs
  src/kernel/src/pm/process/state/running.rs
  src/kernel/src/pm/process/state/zombie.rs
  src/kernel/src/pm/thread/mod.rs
  src/microvm/Cargo.toml
  src/microvm/src/vmm/microvm/kvm/vcpu/mod.rs
  src/tests/arch-rust/Cargo.toml
Labels: enhancement

#967 [contrib] Updating CPython
  Makefile
Labels: enhancement

#971 [scripts] Don't Wrongly Fail on Shell Lint
  scripts/shell-lint-fix.sh
Labels: bug

#969 [libs] Increase Maximum Number of File Descriptors in `poll()`
  src/daemons/linuxd/src/linuxd/assemble.rs
  src/daemons/linuxd/src/message.rs
  src/daemons/linuxd/src/poll.rs
  src/daemons/linuxd/src/worker_thread.rs
  src/libs/sysapi/src/limits.rs
  src/libs/syscall/src/lib.rs
  src/libs/syscall/src/poll/message.rs
  src/libs/syscall/src/poll/syscall.rs
  src/tests/file-c/common.h
  src/tests/file-c/main.c
  src/tests/file-c/poll.c
Labels: enhancement

#976 [ci] Disable Warm-Start Benchmark for MicroVM
  .github/actions/benchmark/action.yml
Labels: bug

#990 [lib] Dummy System Call Implementations
  src/libs/syscall/src/pthread/bindings/mod.rs
  src/libs/syscall/src/pthread/bindings/pthread_atfork.rs
  src/libs/syscall/src/pthread/bindings/pthread_condattr_init.rs
  src/libs/syscall/src/pthread/bindings/pthread_condattr_setclock.rs
Labels: enhancement

#989 [daemons] Fix Race Condition When Connecting To Gateway
  scripts/test-nanvixd.sh
  src/daemons/linuxd/src/linuxd/mod.rs
  src/libs/config/src/lib.rs
  src/libs/syscomm/src/lib.rs
  src/microvm/src/main.rs
  src/utils/nanvixd/src/sandbox/linuxd.rs
  src/utils/nanvixd/src/sandbox/microvm.rs
Labels: bug

#997 [libs] Remove Memory Maps on `munmap()`
  src/libs/config/src/lib.rs
  src/libs/sys/src/sys/config.rs
  src/libs/syscall/src/sys/mman/syscalls/mmap.rs
  src/libs/syscall/src/sys/mman/syscalls/mprotect.rs
  src/libs/syscall/src/sys/mman/syscalls/munmap.rs
  src/tests/testd/src/mm/mod.rs
Labels: enhancement

#1007 [microvm] Properly Catch vCPU Thread Interruption
  src/microvm/src/vmm/microvm/kvm/vcpu/mod.rs
Labels: bug

#1008 [libs] Linux mprotect
  src/libs/syscall/src/sys/mman/syscalls/mprotect.rs
Labels: bug

#1003 [microvm] Remove Gateway Structure
  src/microvm/src/gateway.rs
  src/microvm/src/io_thread.rs
  src/microvm/src/lib.rs
  src/microvm/src/main.rs
  src/microvm/src/vmm/hyperlight/mod.rs
  src/microvm/src/vmm/microvm/mod.rs
  src/utils/nanvix-bench/src/main.rs
Labels: enhancement

#1013 [build] Add cmake To Dependency List
  scripts/setup/Dockerfile
  scripts/setup/ubuntu.sh
Labels: bug

#1019 [libs] Memory Allocation Functions
  Cargo.toml
  Makefile
  src/libs/libc_stdlib/Cargo.toml
  src/libs/libc_stdlib/src/aligned_alloc.rs
  src/libs/libc_stdlib/src/block_header.rs
  src/libs/libc_stdlib/src/calloc.rs
  src/libs/libc_stdlib/src/free.rs
  src/libs/libc_stdlib/src/lib.rs
  src/libs/libc_stdlib/src/malloc.rs
  src/libs/libc_stdlib/src/posix_memalign.rs
  src/libs/libc_stdlib/src/realloc.rs
Labels: feature

#1020 [libs] Check Overflows in mprotect()
  src/libs/syscall/src/sys/mman/syscalls/mprotect.rs
Labels: bug

#1028 [libs] `select()` System Call
  src/daemons/linuxd/Cargo.toml
  src/daemons/linuxd/src/main.rs
  src/daemons/linuxd/src/sys_select.rs
  src/daemons/linuxd/src/worker_thread.rs
  src/libs/posix/src/sys/mod.rs
  src/libs/posix/src/sys/select.rs
  src/libs/sysapi/src/sys_select.rs
  src/libs/syscall/src/lib.rs
  src/libs/syscall/src/sys/mod.rs
  src/libs/syscall/src/sys/select/bindings/mod.rs
  src/libs/syscall/src/sys/select/message/mod.rs
  src/libs/syscall/src/sys/select/mod.rs
  src/libs/syscall/src/sys/select/syscall/mod.rs
  src/tests/file-c/common.h
  src/tests/file-c/main.c
  src/tests/file-c/select.c
Labels: feature
